### ISSUE TITLE
Add an ability to fix eslint errors

### ISSUE THREAD

**Issue by KuzMaxOriginal** [oguilleux/webpack-gulp-wordpress-starter-theme#151]
Currently, there's no script for running eslint with "--fix" option. If you install eslint globally, and run `eslint . --fix`, you will encounter 5k+ errors to be fixed, since it does not omit `gulp` folders and some others. There're also no easy ways to implement it by yourself, since current build pipes js files to preconfigured webpack.

It'd be very useful since, for instance, I often forget to place single quotes instead of double ones, or missing commas.

And thank you for the job that is already done. It's not far from being a separate framework! Best of luck.

**Comment by oguilleux** [comment]
Hi, 

Check out the latest release and tell me if it fixes your problem.
