### ISSUE TITLE
 Unexpected token { in JSON at position 129

### ISSUE THREAD

**Issue by melcarthus** [oguilleux/webpack-gulp-wordpress-starter-theme#399]
**Describe the bug**
When  using single quotes for notifier messages the terminal gives an error ``` Unexpected token { in JSON at position 129```

**To Reproduce**
1. Clone repo
2. Yarn / NPM i etc...
3. Yarn start / npm start
4. See error in terminal

**Expected behavior**
No erros on a clean clone of the repo on startup

**Screenshots**
n.a.

**Additional context**
I think this could be solved by using double quotes.

**Comment by oguilleux** [comment]
Hi @melcarthus, can you pull and tell me if the latest updates on dependencies have solved the issue please ?

**Comment by melcarthus** [comment]
Hi @oguilleux, Apart from some unexpected console statements (which are not a big deal) everything seems alright now!

**Comment by oguilleux** [comment]
I'll stay vigilant because I also saw this warning but the behavior was not stable so I couldn't debug properly.
