### ISSUE TITLE
gulp-svgmin 4.1.0 breaks options

### ISSUE THREAD

**Issue by melcarthus** [oguilleux/webpack-gulp-wordpress-starter-theme#632]
**Describe the bug**
When using the latest version of this repo on my m1 mac my svg's inside the sprites folders should have their fill attributes removed but they are not. When setting gulpsvgmin back to 3.0.0 everything works fine. What could be the cause of this?

I'm using node 16.13.1, but I also tested on v14 and v15.

**Comment by oguilleux** [comment]
Hi @melcarthus,

You're right this was because SVGMIN updated the way the options work. I've made a commit. Tell me if it fixed your problem and close the issue if it did.

Thanks

**Comment by melcarthus** [comment]
Hi @oguilleux,

Thank you for the fast reply. It does not look like this is working either. Maybe its my project that I made some changes to. I'll try a fresh build from your repo and see if there is anything I need to fix on my end.

**Comment by oguilleux** [comment]
Try a watch first.

**Comment by oguilleux** [comment]
Is your fill in `<style>`tag ?

**Comment by melcarthus** [comment]
Hi @oguilleux I figured it out. This was truly an oversight on my part. I did not use any ```<style>``` tags. but i did find a couple of icons that inline styles ```style="fill:#123123;"``` 

The strange thing is that svgmin 3.0.0 did not give me this problem.

**Comment by oguilleux** [comment]
Okay, latest version of the repo uses svgmin `4.1.0`.

**Comment by melcarthus** [comment]
No it’s an attribute.

Van: Olivier Guilleux ***@***.***>
Beantwoorden - Aan: oguilleux/webpack-gulp-wordpress-starter-theme ***@***.***>
Datum: woensdag 6 april 2022 om 21:55
Aan: oguilleux/webpack-gulp-wordpress-starter-theme ***@***.***>
CC: Tim Wolf ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [oguilleux/webpack-gulp-wordpress-starter-theme] gulp-svgmin 4.1.0 breaks options (Issue #632)


Is your fill in a <style>tag ?
