### ISSUE TITLE
How to fire Browsersync?

### ISSUE THREAD

**Issue by wise1999** [oguilleux/webpack-gulp-wordpress-starter-theme#663]
Hi,

I've uncommented out in gulpfile: 

`'browser:sync'`

then I run npm run start, proxy URL is available, but if I go to the browser, the Browsersync shows me an information about pasting thecode snippet before the `</body>` tag. So I've done that, but after refreshing the page, message from Browsersync still occurs. What I'm doing incorrectly?

**Comment by oguilleux** [comment]
Try the `browser-sync-tests` branch. You will need to [define the WP environnement](https://wphelp.blog/wp-environment-type-constant-and-the-wp-get-environment-type-function/).

It's a basic install for http.

**Comment by wise1999** [comment]
Okay, so I've set up the env variable to development and tried this specific branch. But unfortunately still the same browsersync info about code snippet occurs, even while I put it into the footer. :(

**Comment by oguilleux** [comment]
It may be a http or https problem. What is the error exactly ?

**Comment by wise1999** [comment]
I cannot escape from browsersync page with placing code snippet:

`<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.js?v=2.27.10'><\/script>".replace("HOST", location.hostname));
//]]></script>`

into the body tag. Browsersync starts at http://localhost:3001, but when I go to this URL, browsersync page appears instead of the page content.

**Comment by oguilleux** [comment]
Ok so first : 
Be careful this script is already added on the `browser-sync-tests` branch in [this file](https://github.com/oguilleux/webpack-gulp-wordpress-starter-theme/blob/browser-sync-tests/configure/js-css.php).
