### ISSUE TITLE
General Query on adding additonal js files

### ISSUE THREAD

**Issue by Pauldominick** [oguilleux/webpack-gulp-wordpress-starter-theme#777]
Hi, thank you for the amazing build.

I have a question on js files. I am new to coding with a basic knowledge.  

1. If I wanted to add additonal js scripts and wanted to import to the main  js file (eg : import './location/jsfile';). How can I do that?
2.  Is there a detailed step by step guidelines for the entire procedure or somewhere you have published?

Thanks and apologies for these trivial queries. 

Paul

**Comment by oguilleux** [comment]
_If I wanted to add additonal js scripts and wanted to import to the main js file (eg : import './location/jsfile';). How can I do that?_
In main.js you can just do `import myClass from './location/jsfile'` and initialise it the way it's done for the generalScripts or if you don't have a class just `import './location/jsfile'`.

_Is there a detailed step by step guidelines for the entire procedure or somewhere you have published?_
It's basic javascript. You should google terms like `import js`or `classes in javascript import` and learn from tutorials.

Good luck 💪
Closing as this is not an issue.
