### ISSUE TITLE
BrowserSync with PHP files

### ISSUE THREAD

**Issue by NicoGill** [oguilleux/webpack-gulp-wordpress-starter-theme#788]
Hello,

First of all, thanks for the simple and efficient theme ! 

I managed to activate BrowserSync in an environment with Laragon by modifying the file `/gulp/core/config/browser-sync.js` but it does not refresh the browser when modifying a PHP file.

Is there an easy way to do it ?

**Comment by oguilleux** [comment]
Hi @NicoGill,

Thanks :) 

Have you had a look at [this issue ](https://github.com/oguilleux/webpack-gulp-wordpress-starter-theme/issues/663) ?

**Comment by NicoGill** [comment]
Whoops sorry I didn't think to look in the closed issues ! 

Thank you @oguilleux :)
